### ISSUE TITLE
Ar.dump file only has two frames....

### ISSUE THREAD

**Issue by holly-mcenaney** [WSUChem537/General#4]
Hello all!
So from my last issue you can see I was able to complete the simulation... However, when I load the dump file into VMD there are only 2 frames... this does not feel right to me... Any ideas of what might be wrong? Are other people getting more frames from the min simulation?
<img width="492" alt="image" src="https://user-images.githubusercontent.com/97746821/152253366-b1c5dda0-b491-4dca-aebb-5eff4df15de7.png">

**Comment by BobStillwater12** [comment]
I've had the same result of only two frames. I'm guessing that our simulation was already close to a minimum state and that's why we are just getting two frames. We might be able to play with the run minimization choices in the input file to obtain more frames. I believe the first two numbers after minimize represent the tolerance, which might allow the molecules to wiggle around more, but I haven't tested this out yet.

**Comment by brookebonar** [comment]
I am also only getting 2 frames so I am unsure why would all only be getting 2 (as we all chose different box parameters).

**Comment by BobStillwater12** [comment]
I tried my workaround and still only got two frames, so I have no clue what's wrong with it, unfortunately.

**Comment by CatherineMoulder** [comment]
I'm getting plenty of frames on the first dump file and then it's going fubar on the second after three dumps (after time step 73) in the dump.ArEqual.lammpstrj file. On the first dump file (ArEqual.dump for me), everything is great until time step 73 as well.
